server:
  servlet:
    context-path: /api
  port: 8080

placeholder:
  path-param:
    single-post: \{post_id\}

integration:
  comments:
    url: https://jsonplaceholder.typicode.com/comments
  single-post:
    path: https://jsonplaceholder.typicode.com/posts/
    url: ${integration.single-post.path}${placeholder.path-param.single-post}
